from shared.run_me_lib import run_me

def test_run_me_no_exception():
    run_me()

# def test_run_me_with_exception():
#     run_me(0)
